<?php
require_once(dirname(__FILE__) . "/../../config.php");
require_once($CFG->libdir . '/pdflib.php'); // Include Moodle's PDF library

global $CFG, $DB;

$quizid = required_param('quizid', PARAM_INT);
$quiz = $DB->get_record('quiz', ['id' => $quizid], '*', MUST_EXIST);

// Fetch quiz attempts directly, matching the question-wise response logic
$attempts = $DB->get_records_sql(
    "SELECT DISTINCT qa.*
     FROM {quiz_attempts} qa
     JOIN {question_usages} qu ON qu.id = qa.uniqueid
     JOIN {question_attempts} qa2 ON qa2.questionusageid = qu.id
     WHERE qa.quiz = ? AND qa.state = 'finished'",
    [$quizid]
);
$total_attempts = count($attempts);

// Calculate total responses and average time
$total_responses = 0;
$total_time = 0;
foreach ($attempts as $attempt) {
    $total_responses++;
    if ($attempt->timefinish && $attempt->timestart) {
        $total_time += $attempt->timefinish - $attempt->timestart;
    }
}
$average_time = $total_responses ? gmdate('i:s', $total_time / $total_responses) : '00:00';

// Fetch questions for the quiz using question_references
$questions = $DB->get_records_sql(
    "SELECT q.id, q.questiontext
     FROM {quiz_slots} qs
     JOIN {question_references} qr ON qr.itemid = qs.id
         AND qr.component = 'mod_quiz' AND qr.questionarea = 'slot'
     JOIN {question_bank_entries} qbe ON qbe.id = qr.questionbankentryid
     JOIN {question_versions} qv ON qv.questionbankentryid = qbe.id
         AND (qr.version IS NULL OR qv.version = qr.version)
     JOIN {question} q ON q.id = qv.questionid
     WHERE qs.quizid = ?",
    [$quizid]
);

if (empty($questions)) {
    die("No questions found for this quiz. Cannot generate PDF report.");
}

// Fetch question-wise responses
$questionwise_data = [];
foreach ($questions as $question) {
    $responses = $DB->get_records_sql(
        "SELECT qa.responsesummary as answer, COUNT(*) as count
         FROM {question_attempts} qa
         JOIN {question_usages} qu ON qu.id = qa.questionusageid
         JOIN {quiz_attempts} qa2 ON qa2.uniqueid = qu.id
         WHERE qa.questionid = ? AND qa2.quiz = ?
         GROUP BY qa.responsesummary",
        [$question->id, $quizid]
    );
    $questionwise_data[$question->id] = [
        'text' => $question->questiontext,
        'responses' => $responses
    ];
}

// Create a new PDF instance
$pdf = new pdf();

// Set document information
$pdf->SetCreator('Moodle Quiz Report Plugin');
$pdf->SetAuthor('Generated by Moodle');
$pdf->SetTitle('Quiz Report: ' . $quiz->name);
$pdf->SetSubject('Quiz Report');
$pdf->SetKeywords('quiz, report, moodle');

// Set margins
$pdf->SetMargins(15, 15, 15); // Left, Top, Right
$pdf->SetAutoPageBreak(true, 15); // Bottom margin

// Start the PDF document
$pdf->AddPage();

// Generate HTML content for the PDF
$html = '
    <h1>Quiz Report: ' . htmlspecialchars($quiz->name) . '</h1>
    <p><strong>Generated on:</strong> June 11, 2025, 12:04 AM IST</p>

    <h2>Summary</h2>
    <table border="1" cellpadding="5">
        <tr>
            <th width="30%"><strong>Metric</strong></th>
            <th width="70%"><strong>Value</strong></th>
        </tr>
        <tr>
            <td>Total Responses</td>
            <td>' . $total_responses . '</td>
        </tr>
        <tr>
            <td>Average Time Spent</td>
            <td>' . $average_time . '</td>
        </tr>
        <tr>
            <td>Total Attempts</td>
            <td>' . $total_attempts . '</td>
        </tr>
    </table>

    <h2>Question-wise Responses</h2>';

foreach ($questionwise_data as $qid => $qdata) {
    $html .= '<h3>' . htmlspecialchars(strip_tags($qdata['text'])) . '</h3>';
    $html .= '<table border="1" cellpadding="5">';
    $html .= '<tr><th width="70%"><strong>Option</strong></th><th width="30%"><strong>Response Count</strong></th></tr>';
    foreach ($qdata['responses'] as $response) {
        $answer = $response->answer ? htmlspecialchars($response->answer) : 'No response';
        $html .= '<tr><td>' . $answer . '</td><td>' . $response->count . '</td></tr>';
    }
    $html .= '</table>';
}

// Add CSS for better styling
$css = '
    <style>
        h1 { font-size: 24px; text-align: center; }
        h2 { font-size: 20px; margin-top: 20px; }
        h3 { font-size: 16px; margin-top: 15px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 5px; text-align: left; }
        th { background-color: #f2f2f2; }
        p { margin: 5px 0; }
    </style>';

$html = $css . $html;

// Write HTML content to the PDF
$pdf->writeHTML($html);

// Output the PDF as a downloadable file
$pdf->Output('quiz_report_' . $quizid . '.pdf', 'D');
exit;
?>